import pymysql
import sys
try:
    conn = pymysql.connect(host='localhost', user='root', password='', db='aplikasi_data_scientis', charset='utf8mb4')
    cur = conn.cursor()
    cur.execute("SHOW TABLES")
    tables = [row[0] for row in cur.fetchall()]
    outpath = '..\\aplikasi_data_scientis_backup_autodump.sql'
    with open(outpath, 'w', encoding='utf8') as f:
        f.write("-- Backup generated by script\n")
        f.write("CREATE DATABASE IF NOT EXISTS `aplikasi_data_scientis`;\nUSE `aplikasi_data_scientis`;\n\n")
        for t in tables:
            cur.execute(f"SHOW CREATE TABLE `{t}`")
            create = cur.fetchone()[1]
            f.write(f"DROP TABLE IF EXISTS `{t}`;\n")
            f.write(create + ";\n\n")
            cur.execute(f"SELECT * FROM `{t}`")
            rows = cur.fetchall()
            if rows:
                for row in rows:
                    vals = []
                    for v in row:
                        if v is None:
                            vals.append('NULL')
                        else:
                            s = str(v).replace("'", "''")
                            vals.append("'" + s + "'")
                    f.write(f"INSERT INTO `{t}` VALUES ({', '.join(vals)});\n")
                f.write('\n')
    cur.close()
    conn.close()
    print('Backup written to', outpath)
except Exception as e:
    print('Backup failed:', e)
    sys.exit(1)
